version: '3.1'

services:

  elasticsearch:

    image: elasticsearch

    ports:

      - 9200:9200

    volumes:
      - esdata:/usr/share/elasticsearch/data


  kibana:

    image: kibana

    links:

      - elasticsearch:elasticsearch

    ports:

      - 5601:5601

    environment:

      - ELASTICSEARCH_URL=http://elasticsearch:9200

  zookeeper:

    image: zookeeper:latest

    ports:

      - 2181:2181

  kafka:

    image: wurstmeister/kafka

    links:

      - zookeeper:zookeeper

    ports:

      - 9092:9092

    environment:

      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.11"

      KAFKA_ADVERTISED_PORT: "9092"

      KAFKA_CREATE_TOPICS: "topictest:1:1"

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  logstash:

    image: logstash:latest

    links:

      - elasticsearch:elasticsearch

    ports:

      - 12201:12201

    command: logstash -e "input { kafka { bootstrap_servers => '192.168.1.11:9092' client_id =>'logstash' topics => 'topictest' } tcp { port => 12602 codec => json } }  output { elasticsearch { hosts => '192.168.1.11:9200' } }"



volumes:
  esdata:
    driver: local

