version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
